name: sign_wave_v3
description: "SignWave - Real-time communication platform with video calling and messaging features for seamless connectivity."

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  animations: ^2.0.11
  cached_network_image: ^3.4.1
  cherry_toast: ^1.13.0 
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  emoji_picker_flutter: ^4.3.0
  equatable: ^2.0.7
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_contacts: ^1.1.9+2
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^19.1.0
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.3
  googleapis_auth: ^2.0.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.1
  # jitsi_meet_flutter_sdk: ^11.5.1
  flutter_callkit_incoming: ^3.0.0
  flutter_native_splash: ^2.4.1
  cloud_firestore: ^5.6.12

dependency_overrides:
  intl: ^0.19.0
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/logo_android12_padded_1024_60.png
    - secret/sign-language-translator-11862-75c8a47fd8d0.json
    - .env

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo_android12_padded_1024_60.png

  # By removing 'android_gravity: center', the splash screen will fill the screen
  # and the image will be scaled down to fit, preventing it from being cut off.
  android_gravity: center

  ios_content_mode: scaleAspectFit
  web_image_mode: contain

  fullscreen: true

  # Dark mode settings
  color_dark: "#1a1a1a"
  image_dark: assets/images/logo_android12_padded_1024_60.png

  # Android 12+ settings
  android_12:
    image: assets/images/logo_android12_padded_1024_60.png
    color: "#ffffff"
    image_dark: assets/images/logo_android12_padded_1024_60.png
    color_dark: "#1a1a1a"

  # The android, ios and web parameters can be used to disable generating a splash screen on a given
  # platform.
  #android: false
  #ios: false
  #web: false

  # Platform specific images can be specified with the following parameters, which will override
  # the respective parameter.  You may specify all, selected, or none of these parameters:
  #color_android: "#42a5f5"
  #color_dark_android: "#042a49"
  #color_ios: "#42a5f5"
  #color_dark_ios: "#042a49"
  #color_web: "#42a5f5"
  #color_dark_web: "#042a49"
  #image_android: assets/splash-android.png
  #image_dark_android: assets/splash-invert-android.png
  #image_ios: assets/splash-ios.png
  #image_dark_ios: assets/splash-invert-ios.png
  #image_web: assets/splash-web.png
  #image_dark_web: assets/splash-invert-web.png
  #background_image_android: "assets/background-android.png"
  #background_image_dark_android: "assets/dark-background-android.png"
  #background_image_ios: "assets/background-ios.png"
  #background_image_dark_ios: "assets/dark-background-ios.png"
  #background_image_web: "assets/background-web.png"
  #background_image_dark_web: "assets/dark-background-web.png"
  #branding_android: assets/brand-android.png
  #branding_dark_android: assets/brand-dark-android.png
  #branding_ios: assets/brand-ios.png
  #branding_dark_ios: assets/brand-dark-ios.png
  #branding_web: assets/brand-web.png
  #branding_dark_web: assets/brand-dark-web.png

  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  #android_gravity: center
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  #ios_content_mode: center
  #
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center

  # The screen orientation can be set in Android with the android_screen_orientation parameter.
  # Valid parameters can be found here:
  # https://developer.android.com/guide/topics/manifest/activity-element#screen
  #android_screen_orientation: sensorLandscape

  # To hide the notification bar, use the fullscreen parameter.  Has no effect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       The user is expected to swipe up to show it.
  #fullscreen: true

  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove the # characters on the other lines in this section.  Or do not remove the
  # # characters if the default names are used.
  #info_plist_files:
  #  - 'ios/Runner/Info.plist'
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'
