// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKt0Z6Yx1toHmuA9EkjlB0s-nOEqF25Ao',
    appId: '1:1022031179507:android:d6d6a8624443b54cd6d186',
    messagingSenderId: '1022031179507',
    projectId: 'sign-language-translator-11862',
    databaseURL:
        'https://sign-language-translator-11862-default-rtdb.firebaseio.com',
    storageBucket: 'sign-language-translator-11862.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPKZYxcZVbcW5lW0zVXQR5rtgAUVU8NC0',
    appId: '1:1022031179507:ios:edefe0da5ff76422d6d186',
    messagingSenderId: '1022031179507',
    projectId: 'sign-language-translator-11862',
    databaseURL:
        'https://sign-language-translator-11862-default-rtdb.firebaseio.com',
    storageBucket: 'sign-language-translator-11862.firebasestorage.app',
    androidClientId:
        '1022031179507-d0mjq26is4dh850olekn37j4r0i6jkvt.apps.googleusercontent.com',
    iosClientId:
        '1022031179507-ufsftah59uhp8nmppki601tcclu12vtu.apps.googleusercontent.com',
    iosBundleId: 'com.abdullah_t3.sign_wave_v3',
  );
}
